### ISSUE TITLE
About your hackathon experience with Quasar

### ISSUE THREAD

**Issue by nothingismagick** [skarzi/eos_hackathon_london#1]
I saw you used Quasar as a dependency for your EOS hackathon project. I was just curious to find out how your experience went and if you would like to give me some feedback. We are deeply interested in making extreme programming more enjoyable and successful for developers! 

Cheers from the Quasar Team

**Comment by skarzi** [comment]
hi,

Firstly, thank you for your amazing work with quasar!

I tested numerous of the vue ui frameworks at hackathons and for personal/university projects.
EOS hackathon was the first time I tried quasar and it worked pretty well.
Documentation is clear and covers almost everything I needed for EOS hackathon.
Based on examples from docs I have built app really quickly.
The only issue I had was with changing color and size of `float/stack label text` of input text element.

I'm mainly a backend developer. Would you need some extra hand in quasar let me know, I am keen to contribute 🙂

Kind Regards

**Comment by nothingismagick** [comment]
Awesome, thanks for the feedback. We are definitely looking for contributors, and in the mid-term also maintainers - join us on our discord server and find me: https://discord.gg/xAVSQR6 Let's have a conversation!
